name:                record-subsets-aeson
version:             0.1.0.0
github:              "aaronallen8455/record-subsets-aeson"
license:             BSD3
author:              "Aaron Allen"
maintainer:          "aaronallen8455@gmail.com"
copyright:           "2020 Aaron Allen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aaronallen8455/record-subsets-aeson#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- record-subsets
- text

library:
  source-dirs: src

tests:
  record-subsets-aeson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - hedgehog
    - record-subsets
    - record-subsets-aeson
    - tasty
    - tasty-hedgehog
